"""FastAPI server for Presidio Analyzer and Anonymizer."""

import json
import logging
import os
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse, PlainTextResponse
from pydantic import BaseModel, ConfigDict, Field
from presidio_analyzer import AnalyzerEngine, AnalyzerRequest, BatchAnalyzerEngine
from presidio_anonymizer import AnonymizerEngine, DeanonymizeEngine
from presidio_anonymizer.entities import InvalidParamError
from presidio_anonymizer.services.app_entities_convertor import AppEntitiesConvertor

from anonymizers import register_anonymizers
from analyzers import (
    LANGUAGE,
    SPACY_MODEL,
    TRANSFORMERS_MODEL,
    create_analyzer_engine,
)

DEFAULT_PORT = 3000
DEFAULT_BATCH_SIZE = 500
DEFAULT_N_PROCESS = 1

logger = logging.getLogger("presidio-api")


class OperatorRequest(BaseModel):
    """Configuration for one Presidio anonymization operator."""

    model_config = ConfigDict(extra="allow")

    type: str = Field(
        ...,
        description="Registered Presidio operator name.",
        examples=[
            "replace",
            "fake_phone_number",
            "fake_rut",
            "shift_date",
        ],
    )

    new_value: str | None = Field(
        default=None,
        description="Replacement value when using the replace operator.",
        examples=["<PERSONA>"],
    )

    days_shift: int | None = Field(
        default=None,
        description=(
            "Temporal shift in days for shift_date. "
            "Use the same value for all dates in a document to preserve chronology."
        ),
        examples=[90],
    )

    reference_date: str | None = Field(
        default=None,
        description=(
            "ISO-8601 date used as a reference for natural language dates, "
            "for example mañana or ayer."
        ),
        examples=["2026-10-02T00:00:00"],
    )


class AnalyzeRequestBody(BaseModel):
    """Request body for POST /analyze."""

    text: str | list[str] = Field(
        ...,
        description="One text string or a list of text strings.",
        examples=[
            "Fabián Villena trabaja en la Universidad Católica y vive en Santiago."
        ],
    )

    entities: list[str] | None = Field(
        default=None,
        description="Optional entity types to detect.",
        examples=[
            [
                "PERSON",
                "ORGANIZATION",
                "LOCATION",
                "RUT",
                "PHONE_NUMBER",
                "DATE_TIME",
            ]
        ],
    )

    score_threshold: float | None = Field(
        default=None,
        ge=0,
        le=1,
        description="Optional minimum score for recognizer results.",
        examples=[0.5],
    )

    context: list[str] | None = Field(
        default=None,
        description="Optional context words for recognizers.",
    )

    allow_list: list[str] | None = Field(
        default=None,
        description="Optional values that should not be detected.",
    )


class AnonymizeRequestBody(BaseModel):
    """Request body for POST /anonymize."""

    text: str = Field(
        ...,
        min_length=1,
        description="Original text containing the entities to anonymize.",
        examples=[
            "Fabián Villena trabaja en la Universidad Católica y su teléfono es 954687598."
        ],
    )

    analyzer_results: list[dict[str, Any]] = Field(
        ...,
        description="Results returned by POST /analyze.",
        examples=[
            [
                {
                    "entity_type": "PERSON",
                    "start": 0,
                    "end": 14,
                    "score": 0.98,
                },
                {
                    "entity_type": "PHONE_NUMBER",
                    "start": 69,
                    "end": 78,
                    "score": 0.9,
                },
            ]
        ],
    )

    anonymizers: dict[str, OperatorRequest] | None = Field(
        default=None,
        description="Operator configuration per entity type.",
        examples=[
            {
                "PHONE_NUMBER": {
                    "type": "fake_phone_number",
                },
                "RUT": {
                    "type": "fake_rut",
                },
                "DATE_TIME": {
                    "type": "shift_date"
                },
            }
        ],
    )


class DeanonymizeRequestBody(BaseModel):
    """Request body for POST /deanonymize."""

    text: str = Field(
        ...,
        min_length=1,
        description="Text generated by Presidio encrypt anonymization.",
    )

    entities: list[dict[str, Any]] = Field(
        ...,
        description="Items returned by the Presidio anonymization response.",
    )

    deanonymizers: dict[str, OperatorRequest] | None = Field(
        default=None,
        description="Deanonymization operator configuration.",
    )


class AnalyzeAndAnonymizeRequestBody(BaseModel):
    """Request body for POST /analyze+anonymize."""

    text: str = Field(
        ...,
        min_length=1,
        description="Single text to analyze and anonymize.",
        examples=[
            (
                "Fabián Villena (16589785-6) trabaja en la Universidad Católica "
                "y vive en Santiago. Su teléfono es 954687598. "
                "Tiene una cita 26 de noviembre a las 10:00."
            )
        ],
    )

    entities: list[str] | None = Field(
        default=None,
        description="Optional entity types to analyze.",
        examples=[
            [
                "PERSON",
                "ORGANIZATION",
                "LOCATION",
                "RUT",
                "PHONE_NUMBER",
                "DATE_TIME",
            ]
        ],
    )

    score_threshold: float | None = Field(
        default=None,
        ge=0,
        le=1,
        description="Optional minimum score for recognizer results.",
        examples=[0.5],
    )

    context: list[str] | None = Field(
        default=None,
        description="Optional context words for recognizers.",
    )

    allow_list: list[str] | None = Field(
        default=None,
        description="Optional values that should not be detected.",
    )

    anonymizers: dict[str, OperatorRequest] | None = Field(
        default=None,
        description="Operator configuration per entity type.",
        examples=[
            {
                "RUT": {
                    "type": "fake_rut",
                },
                "PHONE_NUMBER": {
                    "type": "fake_phone_number",
                },
                "DATE_TIME": {
                    "type": "shift_date"
                },
            }
        ],
    )


def remove_internal_attributes(results: list[Any]) -> None:
    """Remove internal Presidio metadata before returning results."""
    for result in results:
        if hasattr(result, "recognition_metadata"):
            delattr(result, "recognition_metadata")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize Presidio once when the API starts."""
    logging.basicConfig(
        level=os.getenv("LOG_LEVEL", "INFO"),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    logger.info("Starting Presidio Analyzer")
    logger.info("Language: %s", LANGUAGE)
    logger.info("spaCy model: %s", SPACY_MODEL)
    logger.info("Transformers model: %s", TRANSFORMERS_MODEL)

    analyzer_engine = create_analyzer_engine()

    app.state.analyzer_engine = analyzer_engine
    app.state.batch_engine = BatchAnalyzerEngine(analyzer_engine)

    anonymizer_engine = AnonymizerEngine()
    register_anonymizers(anonymizer_engine)

    app.state.anonymizer_engine = anonymizer_engine
    app.state.deanonymizer_engine = DeanonymizeEngine()

    logger.info("Presidio API started")

    yield

    logger.info("Presidio API stopped")


app = FastAPI(
    title="Presidio Analyzer and Anonymizer API",
    description="Spanish PII analysis with Transformers and Presidio anonymization.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.exception_handler(HTTPException)
async def http_exception_handler(
    request: Request,
    exc: HTTPException,
) -> JSONResponse:
    """Use a consistent JSON error format."""
    return JSONResponse(
        status_code=exc.status_code,
        content={"error": exc.detail},
    )


@app.get("/health", response_class=PlainTextResponse)
def health() -> str:
    """Return service health."""
    return "Presidio Analyzer and Anonymizer service is up"


@app.post(
    "/analyze",
    summary="Analyze PII",
    description="Detect PII entities in one text or a list of texts.",
)
async def analyze(
    payload: AnalyzeRequestBody,
    request: Request,
) -> JSONResponse:
    """Analyze one text or a list of texts."""
    try:
        content = payload.model_dump(exclude_none=True)
        content["language"] = LANGUAGE

        analyzer_request = AnalyzerRequest(content)

        if not analyzer_request.text:
            raise HTTPException(status_code=400, detail="No text provided")

        analyzer_engine: AnalyzerEngine = request.app.state.analyzer_engine
        batch_engine: BatchAnalyzerEngine = request.app.state.batch_engine

        is_batch = isinstance(analyzer_request.text, list)
        texts = analyzer_request.text if is_batch else [analyzer_request.text]

        if not all(isinstance(text, str) and text for text in texts):
            raise HTTPException(
                status_code=400,
                detail="Each text must be a non-empty string",
            )

        batch_size = min(
            len(texts),
            int(os.getenv("BATCH_SIZE", DEFAULT_BATCH_SIZE)),
        )

        n_process = min(
            len(texts),
            int(os.getenv("N_PROCESS", DEFAULT_N_PROCESS)),
        )

        iterator = batch_engine.analyze_iterator(
            texts=texts,
            language=LANGUAGE,
            batch_size=batch_size,
            n_process=n_process,
            entities=analyzer_request.entities,
            score_threshold=analyzer_request.score_threshold,
            correlation_id=analyzer_request.correlation_id,
            return_decision_process=analyzer_request.return_decision_process,
            ad_hoc_recognizers=analyzer_request.ad_hoc_recognizers,
            context=analyzer_request.context,
            allow_list=analyzer_request.allow_list,
            allow_list_match=analyzer_request.allow_list_match,
            regex_flags=analyzer_request.regex_flags,
        )

        results = []

        for text_results in iterator:
            remove_internal_attributes(text_results)
            results.append(text_results)

        response_data = results if is_batch else results[0]

        return JSONResponse(
            content=json.loads(
                json.dumps(
                    response_data,
                    default=lambda item: item.to_dict(),
                    sort_keys=True,
                )
            )
        )

    except HTTPException:
        raise

    except TypeError as exc:
        logger.exception("Invalid /analyze request")
        raise HTTPException(
            status_code=400,
            detail=f"Invalid analyze request: {exc}",
        ) from exc

    except Exception as exc:
        logger.exception("PII analysis failed")
        raise HTTPException(
            status_code=500,
            detail=f"PII analysis failed: {exc}",
        ) from exc


@app.post(
    "/anonymize",
    summary="Anonymize PII",
    description="Anonymize text using results returned by POST /analyze.",
)
async def anonymize(
    payload: AnonymizeRequestBody,
    request: Request,
) -> JSONResponse:
    """Anonymize text with results returned by POST /analyze."""
    try:
        content = payload.model_dump(exclude_none=True)

        operators = AppEntitiesConvertor.operators_config_from_json(
            content.get("anonymizers")
        )

        if AppEntitiesConvertor.check_custom_operator(operators):
            raise HTTPException(
                status_code=400,
                detail="Custom anonymizer operators are not supported",
            )

        analyzer_results = AppEntitiesConvertor.analyzer_results_from_json(
            content["analyzer_results"]
        )

        anonymizer: AnonymizerEngine = request.app.state.anonymizer_engine

        result = anonymizer.anonymize(
            text=content["text"],
            analyzer_results=analyzer_results,
            operators=operators,
        )

        return JSONResponse(content=json.loads(result.to_json()))

    except HTTPException:
        raise

    except InvalidParamError as exc:
        raise HTTPException(
            status_code=422,
            detail=exc.err_msg,
        ) from exc

    except Exception as exc:
        logger.exception("Anonymization failed")
        raise HTTPException(
            status_code=500,
            detail=f"Anonymization failed: {exc}",
        ) from exc


@app.post(
    "/deanonymize",
    summary="Deanonymize encrypted content",
    description="Deanonymize data created with Presidio encrypt anonymization.",
)
async def deanonymize(
    payload: DeanonymizeRequestBody,
    request: Request,
) -> JSONResponse:
    """Deanonymize data created with Presidio's encrypt operator."""
    try:
        content = payload.model_dump(exclude_none=True)

        entities = AppEntitiesConvertor.deanonymize_entities_from_json(content)

        operators = AppEntitiesConvertor.operators_config_from_json(
            content.get("deanonymizers")
        )

        deanonymizer: DeanonymizeEngine = request.app.state.deanonymizer_engine

        result = deanonymizer.deanonymize(
            text=content["text"],
            entities=entities,
            operators=operators,
        )

        return JSONResponse(content=json.loads(result.to_json()))

    except HTTPException:
        raise

    except InvalidParamError as exc:
        raise HTTPException(
            status_code=422,
            detail=exc.err_msg,
        ) from exc

    except Exception as exc:
        logger.exception("Deanonymization failed")
        raise HTTPException(
            status_code=500,
            detail=f"Deanonymization failed: {exc}",
        ) from exc


@app.post(
    "/analyze+anonymize",
    summary="Analyze and anonymize",
    description=(
        "Detect PII entities and anonymize them in one request. "
        "Spanish is always used as the analysis language."
    ),
)
async def analyze_and_anonymize(
    payload: AnalyzeAndAnonymizeRequestBody,
    request: Request,
) -> JSONResponse:
    """Analyze and anonymize a single text in one request."""
    try:
        content = payload.model_dump(exclude_none=True)

        analyzer_content = {
            key: value
            for key, value in content.items()
            if key != "anonymizers"
        }
        analyzer_content["language"] = LANGUAGE

        analyzer_request = AnalyzerRequest(analyzer_content)

        if not analyzer_request.text:
            raise HTTPException(
                status_code=400,
                detail="No text provided",
            )

        if not isinstance(analyzer_request.text, str):
            raise HTTPException(
                status_code=400,
                detail=(
                    "The analyze+anonymize endpoint accepts "
                    "only one text string"
                ),
            )

        analyzer_engine: AnalyzerEngine = request.app.state.analyzer_engine
        anonymizer: AnonymizerEngine = request.app.state.anonymizer_engine

        analyzer_results = analyzer_engine.analyze(
            text=analyzer_request.text,
            language=LANGUAGE,
            entities=analyzer_request.entities,
            score_threshold=analyzer_request.score_threshold,
            correlation_id=analyzer_request.correlation_id,
            return_decision_process=analyzer_request.return_decision_process,
            ad_hoc_recognizers=analyzer_request.ad_hoc_recognizers,
            context=analyzer_request.context,
            allow_list=analyzer_request.allow_list,
            allow_list_match=analyzer_request.allow_list_match,
            regex_flags=analyzer_request.regex_flags,
        )

        anonymizers_config = AppEntitiesConvertor.operators_config_from_json(
            content.get("anonymizers")
        )

        if AppEntitiesConvertor.check_custom_operator(anonymizers_config):
            raise HTTPException(
                status_code=400,
                detail="Custom anonymizer operators are not supported",
            )

        anonymized_result = anonymizer.anonymize(
            text=analyzer_request.text,
            analyzer_results=analyzer_results,
            operators=anonymizers_config,
        )

        remove_internal_attributes(analyzer_results)

        return JSONResponse(
            content={
                "analyzer_results": json.loads(
                    json.dumps(
                        analyzer_results,
                        default=lambda item: item.to_dict(),
                        sort_keys=True,
                    )
                ),
                "anonymized_result": json.loads(
                    anonymized_result.to_json()
                ),
            }
        )

    except HTTPException:
        raise

    except InvalidParamError as exc:
        raise HTTPException(
            status_code=422,
            detail=exc.err_msg,
        ) from exc

    except TypeError as exc:
        logger.exception("Invalid /analyze+anonymize request")
        raise HTTPException(
            status_code=400,
            detail=f"Invalid request: {exc}",
        ) from exc

    except Exception as exc:
        logger.exception("Analyze and anonymize operation failed")
        raise HTTPException(
            status_code=500,
            detail=f"Analyze and anonymize operation failed: {exc}",
        ) from exc


@app.get("/recognizers")
def recognizers(request: Request) -> list[str]:
    """Return recognizers available for Spanish."""
    try:
        analyzer_engine: AnalyzerEngine = request.app.state.analyzer_engine

        return [
            recognizer.name
            for recognizer in analyzer_engine.get_recognizers(LANGUAGE)
        ]

    except Exception as exc:
        logger.exception("Could not retrieve recognizers")
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/supportedentities")
def supported_entities(request: Request) -> list[str]:
    """Return entity types supported by the current NLP engine."""
    try:
        analyzer_engine: AnalyzerEngine = request.app.state.analyzer_engine

        return analyzer_engine.get_supported_entities(LANGUAGE)

    except Exception as exc:
        logger.exception("Could not retrieve supported entities")
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/anonymizers")
def anonymizers(request: Request) -> Any:
    """Return available Presidio anonymization operators."""
    anonymizer: AnonymizerEngine = request.app.state.anonymizer_engine
    return anonymizer.get_anonymizers()


@app.get("/deanonymizers")
def deanonymizers(request: Request) -> Any:
    """Return available Presidio deanonymization operators."""
    deanonymizer: DeanonymizeEngine = request.app.state.deanonymizer_engine
    return deanonymizer.get_deanonymizers()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=int(os.getenv("PORT", DEFAULT_PORT)),
    )